### ISSUE TITLE
OpenQueryStoreDashboard - SQL 2008 R2 - Cannot run Report

### ISSUE THREAD

**Issue by sql-aus-hh** [OpenQueryStore/OpenQueryStore#23] opened 2017-06-27 14:27 UTC
As Enrico had written in one of my last issues... _"Please use SSMS 2016 or 2017"_

I'd just installed SSMS 2016 (Details below) and fixed all upcoming errors (lower/upper cases of ColumnNames)... after that my server needs some seconds to display the following message.

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Ssms.exe
  Application Version:	2015.130.16100.1
  Application Timestamp:	583f1f23
  Fault Module Name:	clr.dll
  Fault Module Version:	4.6.1055.0
  Fault Module Timestamp:	563c0f73
  Exception Code:	c0000005
  Exception Offset:	0000c2c1
  OS Version:	6.1.7601.2.1.0.272.7
  Locale ID:	1031
  Additional Information 1:	b2ed
  Additional Information 2:	b2ed12303fbccd9cddd7799604c15a15
  Additional Information 3:	c27e
  Additional Information 4:	c27eb1bcfd0ec5a7f395adc60f7c28da

Report with fixed columnnames => https://github.com/sql-aus-hh/OpenQueryStore/blob/dev/crashed_Report.rdl

![image](https://user-images.githubusercontent.com/20439825/27591800-1bca8ac0-5b53-11e7-8209-d160e5bd5afc.png)

**Comment by Evdlaar** [comment] 2017-06-27 14:43
This is interesting:-).
Can you download the latest report from GitHub by clicking on the file and then the "raw" button and copy/paste the text inside a new .rdl file locally on your machine?

I had some issues in the past with GitHub and XML documents and I want to make sure this isn't the case.

Thanks!

**Comment by sql-aus-hh** [comment] 2017-06-27 14:48
I'd started with the last raw version of the report to be sure to have the actual one... I'd followed the issues from chrisgraef (?)

So I don't think that that might be the problem...


________________________________
Von: Enrico van de Laar <notifications@github.com>
Gesendet: Dienstag, 27. Juni 2017 16:43
An: OpenQueryStore/OpenQueryStore
Cc: SQL_aus_HH; Author
Betreff: Re: [OpenQueryStore/OpenQueryStore] OpenQueryStoreDashboard - SQL 2008 R2 - Cannot run Report (#23)


This is interesting:-).
Can you download the latest report from GitHub by clicking on the file and then the "raw" button and copy/paste the text inside a new .rdl file locally on your machine?

I had some issues in the past with GitHub and XML documents and I want to make sure this isn't the case.

Thanks!

**Comment by Evdlaar** [comment] 2017-06-27 15:18
Ok perfect thanks!
I'll  see if I can reproduce the issue.

**Comment by sql-williamd** [comment] 2017-08-29 10:31
@sql-aus-hh I would like to close this issue, because I think the latest release of OQS should show that the issue is no longer there. Can you test and let us know? We will close this in a week if we hear nothing back from you.

**Comment by sql-aus-hh** [comment] 2017-08-29 15:27
Hello William

Actually I'm on vacation and will be back in the office on 4th September... I'll download and install the newest report version and check it.

BR

Bjoern

Outlook for Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by Evdlaar** [comment] 2017-09-30 18:02
Hi Bjoern,

Did you have time to check out of this problem still exists?

**Comment by sql-williamd** [comment] 2017-10-06 13:02
Closing this issue as general cleanup. If the issue persists, please contact us again

**Closed by sql-williamd** 2017-10-06 13:02 UTC
Labels: bug
